# Generated by Django 2.2.8 on 2020-05-22 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='社团名称')),
                ('club_category', models.CharField(choices=[('文娱体育', '文娱体育'), ('文化综合', '文化综合'), ('公益实践', '公益实践'), ('学术理论', '学术理论')], max_length=4, verbose_name='社团类别')),
                ('create_time', models.DateField(verbose_name='成立时间')),
                ('running_year', models.IntegerField(default=2020, verbose_name='运行年份')),
                ('description', models.CharField(max_length=50, verbose_name='社团描述')),
                ('purpose', models.CharField(max_length=50, verbose_name='社团宗旨')),
                ('icon', models.ImageField(upload_to='', verbose_name='社团图标')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
                ('club_abbreviation', models.CharField(max_length=10, verbose_name='缩写，用于生成二维码')),
                ('is_active', models.BooleanField(default=True)),
                ('club_status', models.CharField(choices=[('审核中', '审核中'), ('冻结', '冻结'), ('撤销', '撤销'), ('正常', '正常')], max_length=2, verbose_name='社团状态')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='二级单位名称')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=20, verbose_name='专业班级')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Unit', verbose_name='学院')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='活动名称')),
                ('activity_type', models.CharField(choices=[('大型活动', '大型活动'), ('常规活动', '常规活动'), ('素拓活动', '素拓活动')], max_length=12, verbose_name='活动类型')),
                ('description', models.CharField(max_length=200, verbose_name='活动内容')),
                ('venue', models.CharField(max_length=30, verbose_name='活动地点')),
                ('date', models.DateTimeField(verbose_name='活动预计时间')),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
                ('adjust_suggest_ass', models.CharField(max_length=150, null=True)),
                ('adjust_suggest_tea', models.CharField(max_length=150, null=True)),
                ('approved_association', models.BooleanField(default=False)),
                ('send_ass', models.BooleanField(default=False)),
                ('approved_teacher', models.BooleanField(default=False)),
                ('send_tea', models.BooleanField(default=False)),
                ('approved_xuegong', models.BooleanField(default=False)),
                ('send_xue', models.BooleanField(default=False)),
                ('denied', models.BooleanField(default=False)),
                ('request_change', models.BooleanField(default=False)),
                ('ap_status', models.CharField(choices=[('审核中', '审核中'), ('学社联要求修改', '学社联要求修改'), ('学社联同意', '学社联同意'), ('学社联拒绝', '学社联拒绝'), ('等待指导老师审核', '等待指导老师审核'), ('指导老师要求修改', '指导老师要求修改'), ('指导老师已拒绝', '指导老师已拒绝'), ('待举办', '待举办'), ('已完成', '已完成')], max_length=20)),
                ('is_check_over', models.BooleanField(default=False)),
                ('is_over', models.BooleanField(default=False)),
                ('apply_people', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.ClubUserProfile')),
                ('cooperated_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cooper', to='management.Club', verbose_name='协办社团')),
                ('main_club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main', to='management.Club', verbose_name='主办社团')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True, verbose_name='活动开始时间')),
                ('end_date', models.DateTimeField(null=True, verbose_name='活动结束时间')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='活动分数')),
                ('people_count', models.IntegerField(null=True, verbose_name='活动参与人数')),
                ('is_over', models.BooleanField(default=False)),
                ('activity_application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.ActivityApplication')),
            ],
        ),
    ]
