# Generated by Django 2.2.8 on 2020-04-26 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='二级单位名称')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('gender', models.CharField(choices=[('female', '女'), ('male', '男')], max_length=6)),
                ('affiliated_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('gender', models.CharField(choices=[('female', '女'), ('male', '男')], max_length=6)),
                ('affiliated_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='社团名称')),
                ('club_status', models.CharField(choices=[('dj', '冻结'), ('cx', '撤销'), ('zc', '正常')], max_length=2, verbose_name='社团状态')),
                ('club_category', models.CharField(choices=[('wyty', '文娱体育'), ('whzh', '文化综合'), ('gysj', '公益实践'), ('xsll', '学术理论')], max_length=4, verbose_name='社团类别')),
                ('create_time', models.DateField(verbose_name='成立时间')),
                ('particular_year', models.CharField(max_length=4, verbose_name='运行年份')),
                ('description', models.CharField(max_length=50, verbose_name='社团描述')),
                ('purpose', models.CharField(max_length=50, verbose_name='社团宗旨')),
                ('icon', models.ImageField(upload_to='', verbose_name='社团图标')),
                ('affiliated_units', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Unit', verbose_name='挂靠单位')),
                ('affiliated_units2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='affiliated_unit2', to='management.Unit', verbose_name='挂靠单位2')),
                ('guidance_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.Teacher', verbose_name='指导老师')),
                ('guidance_teacher2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='guidance_teacher2', to='management.Teacher', verbose_name='指导老师2')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='president', to='management.Student', verbose_name='会长')),
                ('vice_president1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vicePresident', to='management.Student', verbose_name='副会长')),
                ('vice_president2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vicePresident2', to='management.Student', verbose_name='副会长2')),
                ('vice_president3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vicePresident3', to='management.Student', verbose_name='副会长3')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='活动名称')),
                ('activity_type', models.CharField(choices=[('大型活动', 'Large-scale'), ('常规活动', 'Regular'), ('素拓活动', 'Extension')], max_length=12, verbose_name='活动类型')),
                ('description', models.CharField(max_length=200, verbose_name='活动内容')),
                ('date', models.DateTimeField(verbose_name='活动时间')),
                ('people_count', models.IntegerField(verbose_name='活动参与人数')),
                ('venue', models.CharField(max_length=30, verbose_name='活动地点')),
                ('score', models.IntegerField(verbose_name='活动分数')),
                ('cooperated_club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cooper', to='management.Club', verbose_name='协办社团')),
                ('main_club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main', to='management.Club', verbose_name='主办社团')),
            ],
        ),
    ]
