# Generated by Django 2.2.8 on 2020-05-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='社团名称')),
                ('club_category', models.CharField(choices=[('文娱体育', '文娱体育'), ('文化综合', '文化综合'), ('公益实践', '公益实践'), ('学术理论', '学术理论')], max_length=4, verbose_name='社团类别')),
                ('create_time', models.DateField(verbose_name='成立时间')),
                ('running_year', models.IntegerField(default=2020, verbose_name='运行年份')),
                ('description', models.CharField(max_length=50, verbose_name='社团描述')),
                ('purpose', models.CharField(max_length=50, verbose_name='社团宗旨')),
                ('icon', models.ImageField(upload_to='', verbose_name='社团图标')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
                ('club_abbreviation', models.CharField(max_length=10, verbose_name='缩写，用于生成二维码')),
                ('is_active', models.BooleanField(default=True)),
                ('club_status', models.CharField(choices=[('sh', '审核中'), ('dj', '冻结'), ('cx', '撤销'), ('zc', '正常')], max_length=2, verbose_name='社团状态')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='二级单位名称')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020)),
                ('discipline', models.CharField(blank=True, max_length=200, null=True, verbose_name='专业')),
                ('classname', models.CharField(max_length=20, verbose_name='班级')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Unit', verbose_name='学院')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=30, verbose_name='活动名称')),
                ('activity_type', models.CharField(choices=[('大型活动', '大型活动'), ('常规活动', '常规活动'), ('素拓活动', '素拓活动')], max_length=12, verbose_name='活动类型')),
                ('description', models.CharField(max_length=200, verbose_name='活动内容')),
                ('venue', models.CharField(max_length=30, verbose_name='活动地点')),
                ('date', models.DateTimeField(verbose_name='活动预计时间')),
                ('adjust_suggest', models.CharField(max_length=150)),
                ('approved_association', models.BooleanField(default=False)),
                ('approved_teacher', models.BooleanField(default=False)),
                ('approved_xuegong', models.BooleanField(default=False)),
                ('apply_people', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.ClubUserProfile')),
                ('cooperated_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cooper', to='management.Club', verbose_name='协办社团')),
                ('main_club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main', to='management.Club', verbose_name='主办社团')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('active_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(null=True, verbose_name='活动开始时间')),
                ('end_date', models.DateTimeField(null=True, verbose_name='活动结束时间')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='活动分数')),
                ('people_count', models.IntegerField(null=True, verbose_name='活动参与人数')),
                ('is_over', models.BooleanField(default=False)),
                ('activity_application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.ActivityApplication')),
            ],
        ),
    ]
