# Generated by Django 2.2.8 on 2020-05-02 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Large-scale', '大型活动'), ('Regular', '常规活动'), ('Extension', '素拓活动')], max_length=12, verbose_name='活动类型'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cooperated_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cooper', to='management.Club', verbose_name='协办社团'),
        ),
        migrations.DeleteModel(
            name='ClubUserProfile',
        ),
    ]
