# Generated by Django 2.2.8 on 2020-05-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='year',
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='classname',
            field=models.CharField(max_length=20, verbose_name='专业班级'),
        ),
    ]
