# Generated by Django 2.2.8 on 2020-03-18 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='活动名称')),
                ('activity_type', models.CharField(choices=[('大型活动', 'Large-scale'), ('常规活动', 'Regular'), ('素拓活动', 'Extension')], max_length=12, verbose_name='活动类型')),
                ('description', models.CharField(max_length=200, verbose_name='活动内容')),
                ('date', models.DateTimeField(verbose_name='活动时间')),
                ('people_count', models.IntegerField(verbose_name='活动参与人数')),
                ('venue', models.CharField(max_length=30, verbose_name='活动地点')),
                ('score', models.IntegerField(verbose_name='活动分数')),
                ('cooperated_club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cooper', to='management.Club', verbose_name='协办社团')),
                ('main_club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main', to='management.Club', verbose_name='主办社团')),
            ],
        ),
    ]
