# Generated by Django 2.2.8 on 2020-05-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200502_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_id',
            field=models.CharField(default='jsj', max_length=10, verbose_name='社团ID'),
            preserve_default=False,
        ),
    ]
