# Generated by Django 2.2.8 on 2020-03-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], max_length=6),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], max_length=6),
        ),
    ]
