# Generated by Django 2.2.8 on 2020-05-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200519_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_status',
            field=models.CharField(choices=[('审核中', '审核中'), ('冻结', '冻结'), ('撤销', '撤销'), ('正常', '正常')], max_length=2, verbose_name='社团状态'),
        ),
    ]
