# Generated by Django 2.2.8 on 2020-05-07 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200503_1542'),
        ('management', '0003_club_club_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='cooperated_club',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='main_club',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='club',
            name='club_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='active_id',
            field=models.IntegerField(default=123, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='活动结束时间'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='活动开始时间'),
        ),
        migrations.AddField(
            model_name='club',
            name='club_abbreviation',
            field=models.CharField(default='xhfc', max_length=10, verbose_name='缩写，用于生成二维码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='people_count',
            field=models.IntegerField(null=True, verbose_name='活动参与人数'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='活动分数'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_category',
            field=models.CharField(choices=[('文娱体育', '文娱体育'), ('文化综合', '文化综合'), ('公益实践', '公益实践'), ('学术理论', '学术理论')], max_length=4, verbose_name='社团类别'),
        ),
        migrations.CreateModel(
            name='ActivityApplication',
            fields=[
                ('apply_time', models.DateTimeField(auto_created=True)),
                ('apply_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='活动记录')),
                ('name', models.CharField(max_length=30, verbose_name='活动名称')),
                ('activity_type', models.CharField(choices=[('Large-scale', '大型活动'), ('Regular', '常规活动'), ('Extension', '素拓活动')], max_length=12, verbose_name='活动类型')),
                ('description', models.CharField(max_length=200, verbose_name='活动内容')),
                ('venue', models.CharField(max_length=30, verbose_name='活动地点')),
                ('date', models.DateTimeField(verbose_name='活动预计时间')),
                ('adjust_suggest', models.CharField(max_length=150)),
                ('approved_association', models.BooleanField(default=False)),
                ('approved_teacher', models.BooleanField(default=False)),
                ('approved_xuegong', models.BooleanField(default=False)),
                ('apply_people', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.ClubUserProfile')),
                ('cooperated_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cooper', to='management.Club', verbose_name='协办社团')),
                ('main_club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main', to='management.Club', verbose_name='主办社团')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_application',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.DO_NOTHING, to='management.ActivityApplication'),
            preserve_default=False,
        ),
    ]
