# Generated by Django 2.2.8 on 2020-05-20 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200520_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityapplication',
            name='adjust_suggest',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activityapplication',
            name='apply_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 11, 5, 35, 211072)),
        ),
    ]
