language: python

sudo: false

install:
  - pip install codecov

script:
  - coverage run tests.py && coverage xml -o coverage_A.xml && codecov -f coverage_A.xml -F projectA.xml
  - coverage run tests.py && coverage xml -o coverage_B.xml && codecov -f coverage_B.xml -F projectB.xml


deploy:
  provider: pages
  skip_cleanup: true
  github_token: '2b95a48e6caa41c176340164af93eee8e6f7fa9e' # Set in travis-ci.org dashboard
  on:
    branch: master

