language: python

sudo: false

install:
  - pip install codecov

script:
  - coverage run tests.py && coverage xml coverage_A.xml && coverage -f coverage_A.xml -F projectA
  - coverage run tests.py && coverage xml coverage_B.xml && coverage -f coverage_B.xml -F projectB


deploy:
  provider: pages
  skip_cleanup: true
  github_token: '2b95a48e6caa41c176340164af93eee8e6f7fa9e' # Set in travis-ci.org dashboard
  on:
    branch: master

