language: python

sudo: false

install:
  - pip install codecov

script:
  - coverage run tests.py && coverage xml -o coverage_A.xml && codecov -t "ed348d85-af02-4eaf-8877-accab857ecd0" -f coverage_A.xml
  - coverage run test2.py && coverage xml -o coverage_B.xml && codecov -t "ed348d85-af02-4eaf-8877-accab857ecd0" -f coverage_B.xml -F projectb


deploy:
  provider: pages
  skip_cleanup: true
  github_token: '99021fae7d9a191daca0560b1062bcc91b11a684' # Set in travis-ci.org dashboard
  on:
    branch: master
