coverage:
  status:
    project:
      default: off
      projectA:
        flags:
          - projectA
      projectB:
        flags:
          - projectB

flags:
  projectA:
    paths: true
  projectB:
    paths: true