coverage:
  status:
    project: off
    projectA:
      flags:
        - projectA
    projectB:
      flags:
        - projectB
flags:
  projectA:
    paths: StudentAssociation
  projectB:
    paths:
      - test2.py
