# Generated by Django 2.2.8 on 2020-05-18 14:03

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('tags', models.CharField(max_length=20, verbose_name='标签')),
                ('content', ckeditor.fields.RichTextField(verbose_name='文章内容')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读量')),
                ('zan_num', models.IntegerField(default=0, verbose_name='点赞量')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论量')),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('modify_suggest', ckeditor.fields.RichTextField(verbose_name='修改意见')),
                ('is_validate', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
    ]
