# Generated by Django 2.2.8 on 2020-05-18 23:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200518_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=ckeditor.fields.RichTextField(default='hello', verbose_name='文章简介'),
            preserve_default=False,
        ),
    ]
