# Generated by Django 2.2.8 on 2020-05-20 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20200520_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 11, 5, 35, 201649)),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(choices=[('活动记录', '活动记录'), ('教程分享', '教程分享'), ('日常分享', '日常分享')], max_length=4, verbose_name='标签'),
        ),
    ]
