# Generated by Django 2.2.8 on 2020-04-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclubuser',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
