# Generated by Django 2.2.8 on 2020-04-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200426_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclubuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
