# Generated by Django 2.2.8 on 2020-05-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clubuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuserprofile',
            name='gender',
            field=models.CharField(choices=[('female', '女'), ('male', '男'), ('unknown', '未知')], max_length=7),
        ),
        migrations.AlterField(
            model_name='clubuserprofile',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.StudentClass', verbose_name='职务'),
        ),
    ]
