# Generated by Django 2.2.8 on 2020-05-19 23:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200519_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuserprofile',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 23, 8, 52, 873200)),
        ),
        migrations.AlterField(
            model_name='clubuserprofile',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.StudentClass', verbose_name='班级'),
        ),
    ]
