# Generated by Django 2.2.8 on 2020-05-18 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200503_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='消息内容')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('社联消息', '社联消息'), ('活动消息', '活动消息'), ('论坛消息', '论坛消息')], max_length=4, verbose_name='消息类型')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_from', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_to', to=settings.AUTH_USER_MODEL, verbose_name='接受人')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
