# Generated by Django 2.2.8 on 2020-04-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentclubuser_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclubuser',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='studentclubuser',
            name='nickname',
            field=models.CharField(blank=True, default='用户', max_length=10, null=True),
        ),
    ]
