# Generated by Django 2.2.8 on 2020-05-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='next_url',
            field=models.CharField(default='fda', max_length=120, verbose_name='详情页面'),
            preserve_default=False,
        ),
    ]
