# Generated by Django 2.2.8 on 2020-05-19 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200519_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuserprofile',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 23, 12, 26, 508062)),
        ),
    ]
