# Generated by Django 2.2.8 on 2020-05-20 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200519_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuserprofile',
            name='job',
            field=models.CharField(choices=[('指导老师', '指导老师'), ('会长', '会长'), ('副会长', '副会长'), ('成员', '成员'), ('匿名', '匿名')], default='匿名', max_length=12),
        ),
        migrations.AlterField(
            model_name='clubuserprofile',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 0, 16, 31, 798264)),
        ),
    ]
