# Generated by Django 2.2.8 on 2020-05-20 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200520_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuserprofile',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 11, 5, 35, 198245)),
        ),
    ]
