# Generated by Django 2.2.8 on 2020-05-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200508_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Category', verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text='文章关键词，用来作为SEO中keywords，最好使用长尾词，3-4个足够', null=True, to='blog.Keyword', verbose_name='文章关键词'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Tag', verbose_name='标签'),
        ),
    ]
